schemaVersion: 2.2.0
metadata:
  generateName: northwind-traders
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: none
          name: test
          protocol: http
          targetPort: 8081
        - exposure: public
          name: inventory
          protocol: http
          targetPort: 8080
          path: /
      memoryRequest: 500Mi
      memoryLimit: 6G
      cpuRequest: 1000m
      cpuLimit: 4000m
  - name: northwind-db
    container:
      image: bitnami/postgresql:14.5.0
      commands: ['/bin/sh', '-c', 'pg_isready -U ${POSTGRESQL_USERNAME}']
      env:
        - name: POSTGRESQL_USERNAME
          value: jkube
        - name: POSTGRESQL_PASSWORD
          value: pa33word
      endpoints:
        - exposure: internal
          name: northwind-db
          protocol: tcp
          targetPort: 5432
      memoryRequest: 500Mi
      memoryLimit: 4G
      cpuRequest: 500m
      cpuLimit: 2000m
      mountSources: false
  - name: rabbit-mq
    container:
      image: rabbitmq:3.11-management
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: jkube
        - name: RABBITMQ_DEFAULT_PASS
          value: pa33word
      endpoints:
        - exposure: internal
          name: rabbit-mq
          protocol: tcp
          targetPort: 5672
        - exposure: internal
          name: rabbit-mq-management
          protocol: tcp
          targetPort: 15672
      memoryRequest: 500Mi
      memoryLimit: 4G
      cpuRequest: 500m
      cpuLimit: 2000m
commands:
  - id: package
    exec:
      label: "1. Package"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        source /home/user/.bashrc && mvn clean package
      group:
        kind: build
        isDefault: true
  - id: deploy
    exec:
      label: "2. Deploy"
      component: tools
      commandLine: |
        source /home/user/.bashrc && \
        oc project $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) && \
        mvn clean package oc:build oc:resource oc:apply
      workingDir: ${PROJECT_SOURCE}
  - id: quarkus-dev
    exec:
      label: "3. Start Development Mode"
      component: tools
      commandLine: |
        source /home/user/.bashrc && mvn quarkus:dev
      workingDir: ${PROJECT_SOURCE}/northwind
  - id: run-dev-env
    exec:
      label: "4. JKube Development Session"
      component: tools
      commandLine: |
        source /home/user/.bashrc && mvn oc:remote-dev
      workingDir: ${PROJECT_SOURCE}/northwind
events:
  postStart:
    - package
